### ISSUE TITLE
Move to CopyFair License.

### ISSUE THREAD

**Issue by dpc** [dpc/mioco#52]
I'd like this and probably all Open Source projects of mine, to move to CopyFair License when this license is actually ready. To get more idea on what CopyFair is about:

* http://wiki.p2pfoundation.net/CopyFair_License
* http://commonstransition.org/commons-based-reciprocity-licenses/

I strongly believe that self-sustaining Open&Free Software is important and I think it's a tragedy that so many important Open Source projects are struggling to fund their development and maintenance, while big companies are making a lot profit using them, often without giving back.

Until then this project will stay licensed as MPL2, but I'd like to give everyone a heads up, and gets and "I agree" from everyone before contributing.

**Comment by dpc** [comment]
@jeremyjh @blabaere: As you've already contributed, I'd like to ask for your opinion.

**Comment by dpc** [comment]
Actually, I might try to put this project under: http://fosslawyers.org/the-fair-commons-generic-license-v0/ sooner than later. I guess $100/year, paid to Bitcoin address should be an adequate licensing terms for for-profits.

**Comment by blabaere** [comment]
Given the ridiculously small efforts I have put in mioco, I think you can choose whatever licensing model you like. Regarding potential future contributions, that one is not a problem for me.
So : I agree.

**Comment by polyfractal** [comment]
Honestly, I don't think this is a good idea at all.  It's your project, so you can obviously do as you like, but here are my thoughts:

- Ostensibly, the reason for a CopyFair license is to provide a steady income stream to the developers from commercial entities who do not contribute back.  $100 is a pittance and vastly under values the work, assuming the goal is to make money from it directly. And it doesn't discriminate between large companies and small (e.g. IBM may be using it for millions of machines, but only pay $100).
- Realistically, few companies will ever pay anything with bitcoin.
- The legal language seems distressingly vague and I doubt most companies will want to touch it.
- If money is paid to the project, does it go to the founder?  Committers?  Anyone who "contributes" (documentation, community support, conferences, etc)?  Seems like a great way to cause drama, especially if the procedure is not enshrined in legal language

I work on OSS full-time at my dayjob, so I'm sympathetic to the idea.  But this doesn't seem like a good way to go about it in my opinion.

**Comment by jeremyjh** [comment]
My contributions are small and I do not think you should weight my opinion very heavily but I think these sorts of licenses are more suitable for *products* than for libraries. mioco could be a core part of an import ecosystem of libraries, but a license like this may hold it back, if others do not want to build on top of it. In any case I am fine with whatever you do decide to do with the license.

**Comment by dpc** [comment]
Thanks for feedback!

**Comment by dpc** [comment]
@jeremyjh : I agree that a strange license etc. might hold back some people. 

@polyfractal: I agreed on discriminating small companies. The pricing should be related to company size, true.

I don't understand why companies would have troubles with paying Bitcoin. I actually think that Bitcoin is great: it's worldwide, publicly available, and what's best: fully transparent. Project leaders could use multi-sig wallets to fully transparently hold and distribute funds. Some alternative  form of payment (like PayPal) could be provided but IMO, it's a PITA to deal with, and Bitcoin is great for this purpose. If the only problem is "Bitcoin stigma", I don't really care.

I agree about poor state of the-fair-commons-generic-license-v0 . Right now it's unsuitable for anything serious. The idea is right, but legal matters are hairy by nature, and require a lot of detail.

After I posted this comment I actually chewed on this idea, some of the problems you've raised. I think at least for now it's unrealistic to switch mioco to it, so I'll pass and just keep it MPL2. But I've did some sketch on how this could work in practice: https://github.com/CopyFairCorp/copyfair and contacted people behind CopyFair licenses.

**Comment by polyfractal** [comment]
> I don't understand why companies would have troubles with paying Bitcoin. I actually think that Bitcoin is great: it's worldwide, publicly available, and what's best: fully transparent. [...] If the only problem is "Bitcoin stigma", I don't really care.

I can think of several, not just the "stigma" (although that really shouldn't be discounted either):

- Not all companies want their activity to be open and transparent, because their tech stack gives them a competitive edge.  I work on OSS, and many commercial entities use our software, but some do not wish to be widely known for using it because they feel it is an "edge" over their competition.

- While it might change in the future, the majority of companies do not have a bitcoin account at present.  So any request to wire money would be declined simply because they cannot do it.  If I were to ask my boss today to wire some BTC, the request would be denied for purely practical reasons.
  
- Bitcoin vendors have a bad track record with security and unprofessional behavior, and many companies will not want to open themselves up to potential problems.  A company will trust Chase bank more than Coinbase for example (even though banks have their own share of problems)

- [Bitcoin is illegal in several countries](https://en.wikipedia.org/wiki/Legality_of_bitcoin_by_country), a list which might grow in the future

- Bitcoin stigma is a real thing, like it or not

Anyhow, those are just my opinions, I'm sure plenty of people would disagree :)
