### ISSUE TITLE
Get working with mio-0.5

### ISSUE THREAD

**Issue by canndrew** [dpc/mioco#63]
This would be useful so that we can use it on windows.

**Comment by canndrew** [comment]
There is most of a fix here (https://github.com/canndrew/mioco/tree/mio-0.5) for this. This doesn't fix the problem of event loops not exiting in mio-0.5 though. A workaround is to change the `EventLoop::run` function in mio to pass a value of, say, `Some(1000)` to `run_once` instead of `None`.

**Comment by dpc** [comment]
There's already a branch for mio-0.5 (test-0.5), I forgot to push it during the weekend as it's not working yet. And there's PR for the fix in mio: https://github.com/carllerche/mio/pull/317.

I'll leave that open until the problem is gone. BTW. Pinging me on gitter channel about anything is the best way to get in sync.

**Comment by dpc** [comment]
Pushe to master.
