### ISSUE TITLE
mioco::sync is not sound

### ISSUE THREAD

**Issue by Drakulix** [dpc/mioco#91]
I am pretty sure `mioco::sync` is not sound.

You should not unsafely implement `Send` at this point because that is implying that the object is not moved. Any use of thread scoped variables will completely fail. Also functions relying to be executed on a very specific thread will fail. (Very common for the main thread and UI related libraries.)

If a struct you need to use is not `Send`, you should construct it inside the coroutine. I think `F` should require `Send` in the function signature.
Even with this change, the function is still helpful, as it provides easy and **safe** access to a `thread::scoped` like (and based) api.

**Comment by dpc** [comment]
Hmm... My Send/Sync understanding is only intuitive, so I might have been wrong on so many levels. :) So my reasoning was:

1. Not long before  mioco did not guarantee running anything on any specific thread (it was actually always spawning a new thread, even if one thread was needed, which was fixed recently), so I was not worried about running on a different thread issues.

2. And as the argument closure would run in the thread only when the coroutine is blocked, the Send is unnecessary.

I guess since users can expect 1. to be true now, it's enough reason require Send. I don't know if 2. holds or not, but I guess there could be `unsafe fn sync_unsafe` that does not require `Send` or something.

Can you explain what's the problem with thread scoped variables?

**Comment by dpc** [comment]
@Drakulix Ping. :)

**Comment by Drakulix** [comment]
Oh sorry, I though I answered already.

Well consider this. You create a thread scoped variable and use `mioco::sync`. Your closure accesses this variable and because mioco::sync creates a new thread, although you dont expect it too, because it does not require `Send` or `Sync` your thread scoped variable suddenly contains something different inside that closure.

I get your seconds argument, but that only explains why `Sync` is not needed, because you don't have parallel access. But you still transfer it, which is what Send explains.

Transferring causes another type of problems then parallel access.

**Comment by dpc** [comment]
You're right. Thanks for convincing me. :)

**Comment by Drakulix** [comment]
You should be able to remove FakeSend in that case.

**Comment by dpc** [comment]
Right.

**Comment by Drakulix** [comment]
Fixed?

**Comment by dpc** [comment]
Yes, I believe.
